# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2019.3.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion-2019.3.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pikalm/Projects/ESCA-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pikalm/Projects/ESCA-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2019.3.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/clion-2019.3.1/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pikalm/Projects/ESCA-master/CMakeFiles /home/pikalm/Projects/ESCA-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pikalm/Projects/ESCA-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named clang-tablegen-targets

# Build rule for target.
clang-tablegen-targets: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clang-tablegen-targets
.PHONY : clang-tablegen-targets

# fast build rule for target.
clang-tablegen-targets/fast:
	$(MAKE) -f CMakeFiles/clang-tablegen-targets.dir/build.make CMakeFiles/clang-tablegen-targets.dir/build
.PHONY : clang-tablegen-targets/fast

#=============================================================================
# Target rules for targets named CWE468

# Build rule for target.
CWE468: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CWE468
.PHONY : CWE468

# fast build rule for target.
CWE468/fast:
	$(MAKE) -f src/CMakeFiles/CWE468.dir/build.make src/CMakeFiles/CWE468.dir/build
.PHONY : CWE468/fast

#=============================================================================
# Target rules for targets named ast

# Build rule for target.
ast: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ast
.PHONY : ast

# fast build rule for target.
ast/fast:
	$(MAKE) -f src/AST/CMakeFiles/ast.dir/build.make src/AST/CMakeFiles/ast.dir/build
.PHONY : ast/fast

#=============================================================================
# Target rules for targets named cwe-468

# Build rule for target.
cwe-468: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cwe-468
.PHONY : cwe-468

# fast build rule for target.
cwe-468/fast:
	$(MAKE) -f src/CWE-468/CMakeFiles/cwe-468.dir/build.make src/CWE-468/CMakeFiles/cwe-468.dir/build
.PHONY : cwe-468/fast

#=============================================================================
# Target rules for targets named target

# Build rule for target.
target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 target
.PHONY : target

# fast build rule for target.
target/fast:
	$(MAKE) -f src/target/CMakeFiles/target.dir/build.make src/target/CMakeFiles/target.dir/build
.PHONY : target/fast

#=============================================================================
# Target rules for targets named smt

# Build rule for target.
smt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smt
.PHONY : smt

# fast build rule for target.
smt/fast:
	$(MAKE) -f src/SMT/CMakeFiles/smt.dir/build.make src/SMT/CMakeFiles/smt.dir/build
.PHONY : smt/fast

#=============================================================================
# Target rules for targets named fsm

# Build rule for target.
fsm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fsm
.PHONY : fsm

# fast build rule for target.
fsm/fast:
	$(MAKE) -f src/FSM/CMakeFiles/fsm.dir/build.make src/FSM/CMakeFiles/fsm.dir/build
.PHONY : fsm/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f src/utils/CMakeFiles/utils.dir/build.make src/utils/CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f tests/CMakeFiles/run_tests.dir/build.make tests/CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... intrinsics_gen"
	@echo "... clang-tablegen-targets"
	@echo "... CWE468"
	@echo "... ast"
	@echo "... cwe-468"
	@echo "... target"
	@echo "... smt"
	@echo "... fsm"
	@echo "... utils"
	@echo "... run_tests"
	@echo "... tests"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

